package com.bohpts.messaging.payload.stat;

public enum StatType {
    CHARACTER_LOGGED_IN,
    CHARACTER_LOGGED_OUT,
    CHARACTER_MAIL_SENT,
    CHARACTER_MAIL_ACCEPTED,
    CHARACTER_MAIL_CANCELLED,
    CHARACTER_MAIL_RETURNED,
    CHARACTERS_EXCHANGE_COMPLETED,

    CLAN_MEMBERS_ONLINE
}